//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import Controladores.Sistema;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    
    //Le paso los datos del sistema que se elige en la ventana principal
    private Sistema sistema; //Objeto sistema
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    
    public Menu() {
        initComponents();
        setLocationRelativeTo(null); //Para que la ventana aparezca en el medio de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Fondo = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        Datos = new javax.swing.JMenu();
        Clientes = new javax.swing.JMenuItem();
        Funcionarios = new javax.swing.JMenuItem();
        Tarifa = new javax.swing.JMenuItem();
        Empleados = new javax.swing.JMenu();
        Ingreso = new javax.swing.JMenuItem();
        Envio = new javax.swing.JMenuItem();
        Recepcion = new javax.swing.JMenuItem();
        Managers = new javax.swing.JMenu();
        Estado = new javax.swing.JMenuItem();
        Cliente = new javax.swing.JMenuItem();
        Transacciones = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_Menu.png"))); // NOI18N
        Fondo.setText("jLabel1");

        BarraMenu.setToolTipText("");

        Datos.setText("Datos");

        Clientes.setText("Clientes");
        Clientes.addActionListener(this::Clientes);
        Datos.add(Clientes);

        Funcionarios.setText("Funcionarios");
        Funcionarios.addActionListener(this::Funcionarios);
        Datos.add(Funcionarios);

        Tarifa.setText("Tarifa");
        Tarifa.addActionListener(this::Tarifa);
        Datos.add(Tarifa);

        BarraMenu.add(Datos);

        Empleados.setText("Paquetes");

        Ingreso.setText("Ver/Ingresar");
        Ingreso.addActionListener(this::Ingreso);
        Empleados.add(Ingreso);

        Envio.setText("Envío");
        Envio.addActionListener(this::Envio);
        Empleados.add(Envio);

        Recepcion.setText("Recepción");
        Recepcion.addActionListener(this::Recepcion);
        Empleados.add(Recepcion);

        BarraMenu.add(Empleados);

        Managers.setText("Reportes");

        Estado.setText("Paquetes por Estado");
        Estado.addActionListener(this::R_Estado);
        Managers.add(Estado);

        Cliente.setText("Consulta por Cliente");
        Cliente.addActionListener(this::R_Cliente);
        Managers.add(Cliente);

        Transacciones.setText("Log de Transacciones");
        Transacciones.addActionListener(this::Transacciones);
        Managers.add(Transacciones);

        BarraMenu.add(Managers);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Clientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clientes
        VentanaCliente nueva = new VentanaCliente(sistema);
        nueva.setVisible(true); 
    }//GEN-LAST:event_Clientes

    private void Funcionarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Funcionarios
        VentanaFuncionario nueva = new VentanaFuncionario(sistema);
        nueva.setVisible(true);
    }//GEN-LAST:event_Funcionarios

    private void Tarifa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tarifa
        VentanaTarifas nueva = new VentanaTarifas(sistema);
        nueva.setVisible(true); 
        dispose();
    }//GEN-LAST:event_Tarifa

    private void Ingreso(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso
        if(this.getSistema().getClientes().size() > 0){
            VentanaPaquete nueva = new VentanaPaquete(sistema);
            nueva.setVisible(true);       
        } else {
            JOptionPane.showMessageDialog(this, "No se puede ingresar paquete hasta no cargar al menos un cliente.", "No hay clientes cargados", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Ingreso

    private void R_Estado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Estado
        //LLAMA A LA VENTANA DE ESTADO
    }//GEN-LAST:event_R_Estado

    private void R_Cliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Cliente
        //LLAMA A LA VENTANA
    }//GEN-LAST:event_R_Cliente

    private void Transacciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transacciones
        //LLAMA LA VENTANA DE TRANSACCIONES
    }//GEN-LAST:event_Transacciones

    private void Envio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Envio
        if(this.getSistema().getPaquetes().size() > 0 && this.getSistema().getFuncionarios().size() > 0){
            VentanaIngresarEnvio nueva = new VentanaIngresarEnvio(sistema);
            nueva.setVisible(true);       
        } else if(this.getSistema().getFuncionarios().size() == 0) {
            JOptionPane.showMessageDialog(this, "No se puede ingresar envio hasta no cargar al menos un funcionario.", "No hay funcionarios cargados", ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se puede ingresar envio hasta no cargar al menos un paquete.", "No hay paquetes cargados", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Envio

    private void Recepcion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recepcion
        //LLAMA VENTANA DE RECEPCIONES
    }//GEN-LAST:event_Recepcion


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenu Datos;
    private javax.swing.JMenu Empleados;
    private javax.swing.JMenuItem Envio;
    private javax.swing.JMenuItem Estado;
    private javax.swing.JLabel Fondo;
    private javax.swing.JMenuItem Funcionarios;
    private javax.swing.JMenuItem Ingreso;
    private javax.swing.JMenu Managers;
    private javax.swing.JMenuItem Recepcion;
    private javax.swing.JMenuItem Tarifa;
    private javax.swing.JMenuItem Transacciones;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}//Class