//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import Utils.Utils;
import java.util.*;
import javax.swing.JFrame;
import Controladores.Sistema;
import Modelo.Cliente;
import javax.swing.table.DefaultTableModel;

public class VentanaCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCliente.class.getName());
    
    private Sistema sistema; //Objeto sistema
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    public VentanaCliente(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); //Para que la ventana aparezca en el medio de la pantalla
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Para que no se cierre todo el programa y solo esta ventana
        
        this.sistema = unSistema;
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_1 = new javax.swing.JLabel();
        NuevoCliente = new javax.swing.JToggleButton();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setText("Seleccione la acción que quiere realizar:");

        NuevoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NuevoCliente.setText("Ingresar Cliente");
        NuevoCliente.addActionListener(this::IngresarCliente);

        lbl_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_2.setText("Clientes ingresados en el sistema:");

        lbl_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_3.setText("Para modificar los datos de un cliente debe seleccionar uno de la lista.");

        ListaClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(NuevoCliente)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_3, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_1)
                .addGap(18, 18, 18)
                .addComponent(NuevoCliente)
                .addGap(18, 18, 18)
                .addComponent(lbl_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_3)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarCliente
        VentanaIngresarCliente nuevoCliente = new VentanaIngresarCliente(sistema);
        nuevoCliente.setVisible(true); 
        dispose();
    }//GEN-LAST:event_IngresarCliente

    //Metodo para que cuando se seleccione uno de la lista se pueda modificar
    private void ListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaClientesMouseClicked
        
        int fila = ListaClientes.getSelectedRow(); //Saca la fila seleccionada

        if(fila != -1){ //Verifico que la fila exista
            String nombre = ListaClientes.getValueAt(fila, 0).toString(); //Saco el numero de la fila, la columna es 0 porque uso nombre
            Cliente cliente = Utils.encontrarCliente(sistema.getClientes(), nombre);
            
            if(cliente != null){ //Si el cliente existe abro la ventana de modificar
                VentanaModificarCliente nueva = new VentanaModificarCliente(sistema, cliente);
                nueva.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_ListaClientesMouseClicked

    //Metodo para que aparezcan los clientes en la lista
    public void cargarClientes(){
        
        DefaultTableModel modelo = new DefaultTableModel(); //Defino una nueva tabla
        modelo.addColumn("Nombre"); //Le pongo el nombre a cada columna
        modelo.addColumn("Celular");
        modelo.addColumn("Correo");
        
        //Copio de la lista para no modificar el orden de la original
        ArrayList<Cliente> ordenada = new ArrayList<>(sistema.getClientes());

        //Ordenar alfabeticamente por nombre
        ordenada.sort((c1, c2) -> c1.getNombre().compareToIgnoreCase(c2.getNombre()));
        
        //Para cada cliente lo agrego a la tabla
        for(int i = 0; i < ordenada.size(); i++){
            Cliente c = ordenada.get(i);
            modelo.addRow(new Object[]{c.getNombre(), c.getCelular(), c.getCorreo()}); //Crea un objeto con lso datos que le paso
        }
        
        ListaClientes.setModel(modelo); //Pone los clientes en la tabla
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaClientes;
    private javax.swing.JToggleButton NuevoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    // End of variables declaration//GEN-END:variables
}