/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.table.DefaultTableModel;
import Modelo.Paquete;
import Controladores.Sistema;

/**
 *
 * @author windows
 */
public class VentanaPaquete extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPaquete.class.getName());
    private Sistema sistema;

    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    
    /**
     * Creates new form VentanaPaquete
     */
    public VentanaPaquete(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); 
        this.setSistema(unSistema);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_1 = new javax.swing.JLabel();
        NuevoPaquete = new javax.swing.JToggleButton();
        lbl_2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paquetes");

        lbl_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setText("Seleccione la acción que quiere realizar:");

        NuevoPaquete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NuevoPaquete.setText("Ingresar Paquete");
        NuevoPaquete.addActionListener(this::NuevoPaqueteActionPerformed);

        lbl_2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_2.setText("Paquetes ingresados en el sistema:");

        tblPaquetes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPaquetes.setEnabled(false);
        jScrollPane1.setViewportView(tblPaquetes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(lbl_1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(lbl_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NuevoPaquete)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_1)
                .addGap(18, 18, 18)
                .addComponent(NuevoPaquete)
                .addGap(18, 18, 18)
                .addComponent(lbl_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoPaqueteActionPerformed
        VentanaIngresarPaquete nuevoPaquete = new VentanaIngresarPaquete(sistema);
        nuevoPaquete.setVisible(true); 
        dispose();
    }//GEN-LAST:event_NuevoPaqueteActionPerformed

    public void actualizarTabla(){
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Identificador", "Fecha", "Cliente", "Destinatario", "Direccion", "Departamento", "Peso", "Precio"});

        for (Paquete c : this.getSistema().getPaquetes()) {
            model.addRow(new Object[]{c.getId(), c.getFechaIngreso(), c.getCliente().getNombre(), c.getDestinatario(), c.getDireccion(), c.getDestino(), c.getPeso() + " Grs.", "$" + c.getPrecio()});
        }

        tblPaquetes.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton NuevoPaquete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JTable tblPaquetes;
    // End of variables declaration//GEN-END:variables
}
