//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controladores.Sistema;
import Modelo.Cliente;

public class VentanaModificarCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaModificarCliente.class.getName());

    private Sistema sistema; //Objeto sistema
    private String nombreActual; //Objeto del cliente que le pasan a la ventana
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    
    public VentanaModificarCliente(Sistema unSistema, Cliente unCliente){
        initComponents();
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.sistema = unSistema;
        this.nombreActual = unCliente.getNombre();
        
        //Pongo los datos actuales del cliente en la ventana
        nombreA.setText(unCliente.getNombre());
        celularA.setText(unCliente.getCelular());
        correoA.setText(unCliente.getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Guardar = new javax.swing.JToggleButton();
        Cancelar = new javax.swing.JToggleButton();
        lbl = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoCelular = new javax.swing.JTextField();
        TextoCorreo = new javax.swing.JTextField();
        NombreN = new javax.swing.JLabel();
        CelularN = new javax.swing.JLabel();
        CorreoN = new javax.swing.JLabel();
        nombreA = new javax.swing.JLabel();
        celularA = new javax.swing.JLabel();
        correoA = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre Actual:");

        Celular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Celular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Celular.setText("Celular Actual:");

        Correo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correo.setText("Correo Actual:");

        Guardar.setText("Guardar");
        Guardar.addActionListener(this::ModificarCliente);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(this::Cancelar);

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Ingrese los datos a modificar:");

        NombreN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NombreN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreN.setText("Nombre Nuevo:");

        CelularN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CelularN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CelularN.setText("Celular Nuevo:");

        CorreoN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CorreoN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CorreoN.setText("Correo Nuevo:");

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Los campos que queden vacios no se modificaran.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre)
                    .addComponent(Celular)
                    .addComponent(Correo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nombreA, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(celularA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(correoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CelularN)
                                .addGap(7, 7, 7))
                            .addComponent(NombreN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CorreoN))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreN)
                    .addComponent(nombreA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celular)
                    .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CelularN)
                    .addComponent(celularA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CorreoN)
                    .addComponent(correoA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Si no quiere modificar, se cierra sin hacer nada
    private void Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar
        VentanaCliente nueva = new VentanaCliente(sistema);
        nueva.setVisible(true); 
        dispose();
    }//GEN-LAST:event_Cancelar

    //Metodo que utilizo para sacar los datos que ingresan y luego guardar lo modificado
    private void ModificarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarCliente

        String nombre = TextoNombre.getText().trim();
        String celular = TextoCelular.getText().trim();
        String correo = TextoCorreo.getText().trim();
        
        //Le paso el nombre actual para buscar en la lista el objeto cliente a modificar y los datos
        if(sistema.ModificarCliente(this.nombreActual, nombre, celular, correo)){
            JOptionPane.showMessageDialog(this, "Cliente modificado correctamente.");                          
            VentanaCliente nueva = new VentanaCliente(sistema);
            nueva.setVisible(true); 
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Error, no se pudo modificar el cliente.");
        }
    }//GEN-LAST:event_ModificarCliente

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Cancelar;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel CelularN;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel CorreoN;
    private javax.swing.JToggleButton Guardar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreN;
    private javax.swing.JTextField TextoCelular;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JLabel celularA;
    private javax.swing.JLabel correoA;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel nombreA;
    // End of variables declaration//GEN-END:variables
}