/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Utils.Utils;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import Modelo.Cliente;
import Modelo.Fecha;
import Controladores.Sistema;
import Excepciones.ErrorFechaNoValidaException;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import static Utils.Utils.stringEsParseableAInt;

/**
 *
 * @author windows
 */
public class VentanaIngresarPaquete extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngresarPaquete.class.getName());
    private static final String[] departamentos = { "Seleccionar", "ARTIGAS", "CANELONES", "CERRO LARGO", "COLONIA", "DURAZNO", "FLORES", "FLORIDA", "LAVALLEJA", "MALDONADO", "MONTEVIDEO", "PAYSANDU", "RIO NEGRO", "RIVERA", "ROCHA", "SALTO", "SAN JOSE", "SORIANO", "TACUAREMBO", "TREINTA Y TRES"};
    private Sistema sistema;

    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    
    /**
     * Creates new form VentanaPaquete
     */
    public VentanaIngresarPaquete(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); 
        this.setSistema(unSistema);
        this.cargarClientes();
        this.cargarDepartamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCliente = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblDestinatario = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cmbCliente = new javax.swing.JComboBox<>();
        txtDireccion = new javax.swing.JTextField();
        cmbDepartamento = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JTextField();
        lblPrecioCalculado = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblSepDia = new javax.swing.JLabel();
        txtFechaDia = new javax.swing.JTextField();
        lblSepMes = new javax.swing.JLabel();
        txtFechaMes = new javax.swing.JTextField();
        txtFechaAnio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Paquete");
        setUndecorated(true);

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCliente.setText("Cliente:");

        lblId1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId1.setText("Identificador:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setText("Fecha (dd/mm/aaaa o dd/mm/aa):");

        lblDestinatario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDestinatario.setText("Destinatario:");

        lblDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDepartamento.setText("Departamento:");

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDireccion.setText("Dirección:");

        lblPeso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPeso.setText("Peso (grs):");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrecio.setText("Precio calculado:");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        cmbCliente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        cmbDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDepartamento.addActionListener(this::calcularPrecios);

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarPeso(evt);
            }
        });

        lblPrecioCalculado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPrecioCalculado.setText("Ingresar departamento y peso para calcular");

        txtDestinatario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lblSepDia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblSepDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSepDia.setText("/");

        txtFechaDia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtFechaDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarDia(evt);
            }
        });

        lblSepMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblSepMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSepMes.setText("/");

        txtFechaMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtFechaMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarMes(evt);
            }
        });

        txtFechaAnio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtFechaAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarAnio(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecioCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId1)
                            .addComponent(lblCliente)
                            .addComponent(lblFecha)
                            .addComponent(lblDestinatario)
                            .addComponent(lblDireccion)
                            .addComponent(lblDepartamento)
                            .addComponent(lblPeso))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId)
                            .addComponent(txtDireccion)
                            .addComponent(cmbDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPeso)
                            .addComponent(txtDestinatario)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtFechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSepDia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(txtFechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSepMes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSepDia)
                    .addComponent(lblSepMes)
                    .addComponent(txtFechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestinatario)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamento)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lblPrecioCalculado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        VentanaPaquete nueva = new VentanaPaquete(sistema);
        nueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void calcularPrecios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularPrecios
        String depto = cmbDepartamento.getSelectedItem().toString();
        String pesoStr = txtPeso.getText().trim();
        
        if(depto != "Seleccionar" && stringEsParseableAInt(pesoStr) && Integer.parseInt(pesoStr) > 0){
            int peso = Integer.parseInt(pesoStr);
            String precioCalculado = "$ " + this.getSistema().precioPaquete(depto, peso);
            lblPrecioCalculado.setText(precioCalculado);
        } else{
            lblPrecioCalculado.setText("Ingresar departamento y peso para calcular");
        }
    }//GEN-LAST:event_calcularPrecios

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            boolean esValido = true;
            String id = txtId.getText().trim();

            Cliente cliente = this.getSistema().encontrarCliente(cmbCliente.getSelectedItem().toString());
            String destinatario = txtDestinatario.getText().trim();
            String direccion = txtDireccion.getText().trim();
            String departamento = cmbDepartamento.getSelectedItem().toString().trim();

            //Parseo de fecha -> Tira excepcion si no son valores numericos
            int dia = Integer.parseInt(txtFechaDia.getText().trim());                                     
            int mes = Integer.parseInt(txtFechaMes.getText().trim());
            int anio = Integer.parseInt(txtFechaAnio.getText().trim());
            Fecha fecha = Fecha.parseFecha(dia, mes, anio); //-> tira excepcion si es una fecha invalida

            //Parseo de peso -> Tira excepcion si no es un valor numerico
            int peso = Integer.parseInt(txtPeso.getText().trim());

            //Validar
            esValido &= !(id.isEmpty() || cliente == null || destinatario.isEmpty() || direccion.isEmpty() || departamento.equalsIgnoreCase("Seleccionar") || peso <= 0); //Ningun valor esta vacio
            if(esValido){
                //Guardar en el sistema
                if(!sistema.guardarPaquete(id, cliente, fecha, destinatario, direccion, departamento, peso)){
                    JOptionPane.showMessageDialog(this, "Ya existe un Paquete con ese identificador, ingrese otro.", "Error al guardar paquete", ERROR_MESSAGE); //Pide otro nombre
                }
                else{
                    JOptionPane.showMessageDialog(this, "Paquete guardado correctamente.");
                    VentanaPaquete nueva = new VentanaPaquete(sistema);
                    nueva.setVisible(true);
                    this.dispose();
                } 
            }
            else{
                JOptionPane.showMessageDialog(this, "Debe ingresar un todos los datos.", "Error al guardar paquete", ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex){
            //Loggear el error
            JOptionPane.showMessageDialog(this, "La fecha y el peso deben ser valores numéricos.", "Error al guardar paquete", ERROR_MESSAGE);
        } catch(ErrorFechaNoValidaException ex) {
            //Loggear el error
            JOptionPane.showMessageDialog(this, "El formato de fecha es inválida o se ingresó una fecha incorrecta.", "Error al guardar paquete", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void validarPeso(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarPeso
        String peso = txtPeso.getText();
        if(peso.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            if(stringEsParseableAInt(peso)){
                this.calcularPrecio();
            } else{
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros enteros.", "Input inválido", ERROR_MESSAGE);
                while(!stringEsParseableAInt(peso) && peso.length() > 0){
                    borrarUltimoChar(txtPeso);
                    peso = txtPeso.getText();
                }
                this.calcularPrecio();
            }
        } else if(peso.length() == 0) {
            this.calcularPrecio();
        }
    }//GEN-LAST:event_validarPeso

    private void validarDia(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarDia
        String dia = txtFechaDia.getText().trim();
        if(dia.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            boolean esValido = stringEsParseableAInt(dia) && Integer.parseInt(dia) > 0 && Integer.parseInt(dia) < 32;
            if(!esValido){ //Si el dia no es un numero, o no estra entre 1 y 31, mostrar mensaje de error y borrar el dato
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros del 1 al 31.", "Input inválido", ERROR_MESSAGE);
                while(!esValido && dia.length() > 0){
                    borrarUltimoChar(txtFechaDia);
                    dia = txtFechaDia.getText().trim();
                    esValido = stringEsParseableAInt(dia) && Integer.parseInt(dia) > 0 && Integer.parseInt(dia) < 32;
                }
            }
        }
    }//GEN-LAST:event_validarDia

    private void validarMes(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarMes
        String mes = txtFechaMes.getText().trim();
        if(mes.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            boolean esValido = stringEsParseableAInt(mes) && Integer.parseInt(mes) > 0 && Integer.parseInt(mes) < 13;
            if(!esValido){ //Si el dia no es un numero, o no estra entre 1 y 31, mostrar mensaje de error y borrar el dato
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros del 1 al 12.", "Input inválido", ERROR_MESSAGE);
                while(!esValido && mes.length() > 0){
                    borrarUltimoChar(txtFechaMes);
                    mes = txtFechaMes.getText().trim();
                    esValido = stringEsParseableAInt(mes) && Integer.parseInt(mes) > 0 && Integer.parseInt(mes) < 13;
                }
            }
        }
    }//GEN-LAST:event_validarMes

    private void validarAnio(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarAnio
        String anio = txtFechaAnio.getText().trim();
        if(anio.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            boolean esValido = stringEsParseableAInt(anio) && Integer.parseInt(anio) > 0 && Integer.parseInt(anio) < 4000;
            if(!esValido){ //Si el dia no es un numero, o no estra entre 1 y 31, mostrar mensaje de error y borrar el dato
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros del 0 al 3000.", "Input inválido", ERROR_MESSAGE);
                while(!esValido && anio.length() > 0){
                    borrarUltimoChar(txtFechaAnio);
                    anio = txtFechaAnio.getText().trim();
                    esValido = stringEsParseableAInt(anio) && Integer.parseInt(anio) > 0 && Integer.parseInt(anio) < 4000;
                }
            }
        }
    }//GEN-LAST:event_validarAnio

    private void borrarUltimoChar(JTextField campo){
        String texto = campo.getText();
        if(texto.length() > 0){
            campo.setText(texto.substring(0, texto.length() - 1));
        }
    }
    
    private void calcularPrecio(){
        String depto = cmbDepartamento.getSelectedItem().toString();
        String pesoStr = txtPeso.getText().trim();
        
        if(depto != "Seleccionar" && stringEsParseableAInt(pesoStr) && Integer.parseInt(pesoStr) > 0){
            int peso = Integer.parseInt(pesoStr);
            String precioCalculado = "$ " + this.getSistema().precioPaquete(depto, peso);
            lblPrecioCalculado.setText(precioCalculado);
        } else{
            lblPrecioCalculado.setText("Ingresar departamento y peso para calcular");
        }
    }
    
    private void cargarClientes(){
        ArrayList<String> nombresClientes = new ArrayList<String>();
        nombresClientes.add("Seleccionar");
        Iterator<Cliente> it = this.getSistema().getClientes().iterator();
        while(it.hasNext()){ //recorro el arraylist de clientes y los agrego de a uno al modelo
            Cliente c = it.next();
            nombresClientes.add(c.getNombre());
        }
        cmbCliente.setModel(new DefaultComboBoxModel(nombresClientes.toArray())); //Asigno la lista modelo al jlist
    }
    
    private void cargarDepartamentos(){
        cmbDepartamento.setModel(new DefaultComboBoxModel(departamentos)); //Asigno la lista modelo al jlist
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioCalculado;
    private javax.swing.JLabel lblSepDia;
    private javax.swing.JLabel lblSepMes;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaAnio;
    private javax.swing.JTextField txtFechaDia;
    private javax.swing.JTextField txtFechaMes;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
