//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controladores.Sistema;

public class VentanaModificarTarifas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaModificarTarifas.class.getName());

    //Le paso los datos del sistema que se elige en la ventana principal
    private Sistema sistema; //Objeto sistema
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    
    public VentanaModificarTarifas(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.sistema = unSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Aumentar = new javax.swing.JRadioButton();
        Disminuir = new javax.swing.JRadioButton();
        Porcentaje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Seleccione la opción que desee e ingrese el porcentaje a modificar:");

        Aumentar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Aumentar.setText("Aumento de precios");

        Disminuir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Disminuir.setText("Disminución de precios");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Porcentaje a modificar:");

        Modificar.setText("Modificar");
        Modificar.addActionListener(this::MoodificarTarifas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Disminuir)
                    .addComponent(Aumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Modificar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aumentar)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Disminuir)
                    .addComponent(Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(Modificar)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoodificarTarifas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoodificarTarifas
        
        //Salta un caudro que pide verificar, con un si o no
        int verifico = JOptionPane.showConfirmDialog(this, "Si modifica las tarifas,"
                + " se aplicara el cambio a todas las categorias y en todas las zonas.\n¿Desea continuar?", "¡ATENCIÓN!",
                JOptionPane.YES_NO_OPTION);
        
        if(verifico == JOptionPane.YES_OPTION){ //Si dice que si, se modifica segun el boton seleccionado
            //codifgo que llame metodo de disminuir o aumentar
            dispose();    
        }
    }//GEN-LAST:event_MoodificarTarifas


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aumentar;
    private javax.swing.JRadioButton Disminuir;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Porcentaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}