/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Controladores.Sistema;
import Modelo.Envio;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;

/**
 *
 * @author windows
 */
public class VentanaRecepcion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRecepcion.class.getName());
    private Sistema sistema;
    
    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    /**
     * Creates new form VentanaRecepcion
     */
    public VentanaRecepcion(Sistema sistema) {
        initComponents();
        setLocationRelativeTo(null); 
        this.setSistema(sistema);
        
        lstEnvios.setCellRenderer(new DefaultListCellRenderer(){
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component celda = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                
                if(!isSelected){
                    Envio envio = (Envio)value;
                    if (envio.getEstado().equalsIgnoreCase("CREADO")) {
                        celda.setBackground(Color.YELLOW);
                    } else{
                        celda.setBackground(Color.GREEN);
                    }
                }
                return celda;
            }
        });
        
        cargarEnvios();
    }
    
    private void cargarEnvios(){
        ArrayList<Envio> envios = new ArrayList<Envio>(this.getSistema().getEnvios());;
        
        Collections.sort(envios);
        lstEnvios.setListData(envios.toArray(Envio[]::new));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEnvios = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstEnvios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstEnvios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEnvios.addListSelectionListener(this::lstEnviosValueChanged);
        jScrollPane1.setViewportView(lstEnvios);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Envíos:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Haga click en un envio para ver mas detalles o editar cuando sea posible");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstEnviosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEnviosValueChanged
        Envio envioSeleccionado = lstEnvios.getSelectedValue();
        if(envioSeleccionado.getEstado().equalsIgnoreCase("CREADO")){
            new VentanaRecibirEnvio(sistema, envioSeleccionado).setVisible(true);
        } else {
            new VentanaDetallesEnvio(sistema, envioSeleccionado).setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_lstEnviosValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Envio> lstEnvios;
    // End of variables declaration//GEN-END:variables
}
