//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controladores.Sistema;
import Modelo.Fecha;
import Utils.Utils;
import static Utils.Utils.stringEsParseableAInt;
import java.awt.event.KeyEvent;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextField;

public class VentanaIngresarFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngresarFuncionario.class.getName());

    private Sistema sistema; //Objeto sistema
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    public VentanaIngresarFuncionario(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.sistema = unSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Anio = new javax.swing.JLabel();
        Guardar = new javax.swing.JToggleButton();
        Cancelar = new javax.swing.JToggleButton();
        lbl = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoCelular = new javax.swing.JTextField();
        TextoNumero = new javax.swing.JTextField();
        Numero1 = new javax.swing.JLabel();
        TextoAnio = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre:");

        Celular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Celular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Celular.setText("Celular:");

        Anio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Anio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anio.setText("Año de Ingreso");

        Guardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(this::GuardarFuncionario);

        Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(this::Cancelar);

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Ingrese los siguientes datos:");

        TextoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TextoCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        TextoNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextoNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextoNumeroKeyReleased(evt);
            }
        });

        Numero1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Numero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Numero1.setText("Número de Funcionario");

        TextoAnio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextoAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextoAnioKeyReleased(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nuevo Funcionario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addComponent(Celular)
                            .addComponent(Numero1)
                            .addComponent(Anio)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celular)
                    .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anio)
                    .addComponent(TextoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar
        VentanaFuncionario nueva = new VentanaFuncionario(sistema);
        nueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cancelar

    private void GuardarFuncionario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarFuncionario
        String nombre = TextoNombre.getText().trim();
        String celular = TextoCelular.getText().trim();
        int anio = 0;
        
        boolean validarAnio = Utils.stringEsParseableAInt(TextoAnio.getText());
        if(validarAnio){
            anio = Integer.parseInt(TextoAnio.getText().trim());
            validarAnio = Fecha.anioValido(anio, 2027);
        }
        
        int numero = 0;
        
        boolean validarNumero = Utils.stringEsParseableAInt(TextoNumero.getText().trim());
        if(validarNumero){
            numero = Integer.parseInt(TextoNumero.getText().trim());
        }

        //Validar
        if(nombre.isEmpty() || celular.isEmpty() || numero == 0 || anio == 0){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre, un celular, un numero de funcionario y un año de ingreso del 1 al 2026.");
        } else if(!validarAnio){
            JOptionPane.showMessageDialog(this, "El año debe ser un valor numérico entre el 1 al 2026 y con formato \"yy\" o \"yyyy\"", "Error al guardar funcionario", ERROR_MESSAGE);
        } else if(!validarNumero){
            JOptionPane.showMessageDialog(this, "El numero de funcionario debe ser un valor numérico.", "Error al guardar funcionario", ERROR_MESSAGE);
        } else {
            //Guardar en el sistema
            if(!sistema.guardarFuncionario(nombre, celular, numero, anio)){
                JOptionPane.showMessageDialog(this, "Ya existe un cliente o funcionario con ese nombre, ingrese otro.");
            } else{
                JOptionPane.showMessageDialog(this, "Funcionario guardado correctamente.");
                VentanaFuncionario nueva = new VentanaFuncionario(sistema);
                nueva.setVisible(true);
                this.dispose();
            }       
        }
    }//GEN-LAST:event_GuardarFuncionario

    private void TextoAnioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoAnioKeyReleased
        String anio = TextoAnio.getText().trim();
        if(anio.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            boolean esValido = stringEsParseableAInt(anio) && Integer.parseInt(anio) > 0 && Integer.parseInt(anio) < 2027; //Solo permitimos año de ingreso hasta el año actual
            if(!esValido){ //Si el año no es un numero, o no estra entre 1 y 2026, mostrar mensaje de error y borrar el dato
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros del 1 al 2026.", "Input inválido", ERROR_MESSAGE);
                while(!esValido && anio.length() > 0){
                    borrarUltimoChar(TextoAnio);
                    anio = TextoAnio.getText().trim();
                    esValido = stringEsParseableAInt(anio) && Integer.parseInt(anio) > 0 && Integer.parseInt(anio) < 2027;
                }
            }
        }
    }//GEN-LAST:event_TextoAnioKeyReleased

    private void TextoNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoNumeroKeyReleased
        String numero = TextoNumero.getText().trim();
        if(numero.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            boolean esValido = stringEsParseableAInt(numero); 
            if(!esValido){ //Si el numero de funcionario  no es un numero, mostrar mensaje de error y borrar el dato
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar números.", "Input inválido", ERROR_MESSAGE);
                while(!esValido && numero.length() > 0){
                    borrarUltimoChar(TextoNumero);
                    numero = TextoNumero.getText().trim();
                    esValido = stringEsParseableAInt(numero);
                }
            }
        }
    }//GEN-LAST:event_TextoNumeroKeyReleased

    private void borrarUltimoChar(JTextField campo){
        String texto = campo.getText();
        if(texto.length() > 0){
            campo.setText(texto.substring(0, texto.length() - 1));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anio;
    private javax.swing.JToggleButton Cancelar;
    private javax.swing.JLabel Celular;
    private javax.swing.JToggleButton Guardar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Numero1;
    private javax.swing.JTextField TextoAnio;
    private javax.swing.JTextField TextoCelular;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoNumero;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}