//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import Controladores.Sistema;
import Modelo.Cliente;
import Modelo.Paquete;
import Utils.Utils;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


public class VentanaReporteCliente2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReporteCliente2.class.getName());

    private Sistema sistema; //Objeto sistema
    private String nombreActual; ///////////
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    
    public VentanaReporteCliente2(Sistema unSistema, Cliente unCliente) {
        initComponents();
        setLocationRelativeTo(null); //Para que la ventana aparezca en el medio de la pantalla
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Para que no se cierre todo el programa y solo esta ventana
        this.nombreActual = unCliente.getNombre();///////
        
        this.sistema = unSistema;
        cargarPaquetesCliente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPaquetes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Reporte de paquetes por cliente:");

        ListaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListaPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaPaquetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaPaquetes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo para que cuando se seleccione uno de la lista se pueda ver el reporte
    private void ListaPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaPaquetesMouseClicked
        
        int fila = ListaPaquetes.getSelectedRow(); //Saca la fila seleccionada

        if(fila != -1){ //Verifico que la fila exista
            String nombre = ListaPaquetes.getValueAt(fila, 0).toString();
            Cliente cliente = Utils.encontrarCliente(sistema.getClientes(), nombre);
            
            if(cliente != null){ //Si el cliente existe abro la ventana de reporte
                VentanaReporteCliente2 nueva = new VentanaReporteCliente2(sistema, cliente);
                nueva.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_ListaPaquetesMouseClicked

    //Metodo para que aparezcan los paquetes en la lista
    public void cargarPaquetesCliente(){
        
        DefaultTableModel modelo = new DefaultTableModel(); //Defino una nueva tabla
        modelo.addColumn("Estado"); //Le pongo el nombre a cada columna
        modelo.addColumn("Identificador");
        modelo.addColumn("Fecha de Ingreso");       
        modelo.addColumn("Destinatario");
        modelo.addColumn("Direccion");
        modelo.addColumn("Departamento");
        modelo.addColumn("Peso");
        modelo.addColumn("Precio");
        
        //Copio de la lista para no modificar el orden de la original
        ArrayList<Paquete> ordenada = this.getSistema().getPaquetesPorCliente(this.nombreActual);
        
        //Ordenar alfabeticamente por estado
        ordenada.sort((c1, c2) -> c1.getEstado().compareToIgnoreCase(c2.getEstado()));
        
        //Para cada cliente lo agrego a la tabla
        for(int i = 0; i < ordenada.size(); i++){
            Paquete p = ordenada.get(i);
            //if(p.getCliente(.getNombre() == nombreActual))
            modelo.addRow(new Object[]{p.getEstado(), p.getId(), p.getFechaIngreso(), p.getDestinatario(), p.getDireccion(),
                                       p.getDestino(), p.getPeso() + " Grs.", "$" + p.getPrecio()});
        }
        
        ListaPaquetes.setModel(modelo); //Pone los clientes en la tabla
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaPaquetes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}