/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Controladores.Sistema;
import Modelo.Envio;
import Modelo.Paquete;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author windows
 */
public class VentanaRecibirEnvio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRecibirEnvio.class.getName());
    private Sistema sistema;
    private Envio envio;
    
    //<editor-fold desc="Getter y setters">
    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    
    public Envio getEnvio() {
        return envio;
    }

    public void setEnvio(Envio envio) {
        this.envio = envio;
    }
    //</editor-fold>

    /**
     * Creates new form VentanaRecibirEnvio
     */
    public VentanaRecibirEnvio(Sistema sistema, Envio envio) {
        initComponents();
        setLocationRelativeTo(null); 
        this.setSistema(sistema);
        this.setEnvio(envio);
        lblID.setText("" + this.getEnvio().getNumeroEnvio());
        lblNombreFuncionario.setText(this.getEnvio().getFuncionario().getNombre());
        lblNumeroFuncionario.setText(this.getEnvio().getFuncionario().getNumero());
        lblZona.setText(this.getEnvio().getNombreZona());
        lblFecha.setText(this.getEnvio().getFechaEnvio().toString());
        cargarPaquetes();
    }
    
    public void cargarPaquetes(){
        
        btnAgregar.setEnabled(false);
        btnRemover.setEnabled(false);
        
        ArrayList<Paquete> paquetesEnviados = new ArrayList<Paquete>(this.getEnvio().getPaquetes());
        Collections.sort(paquetesEnviados);

        //Por defecto asumimos que todos los paquetes fueron entregados
        lstEntregados.setListData(paquetesEnviados.toArray(Paquete[]::new));

        lstNoEntregados.setListData(new Paquete[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnvioTitulo = new javax.swing.JLabel();
        lblNombreFuncionarioTitulo = new javax.swing.JLabel();
        lblNumeroFuncionarioTitulo = new javax.swing.JLabel();
        lblZonaTitulo = new javax.swing.JLabel();
        lblPaquetesTitulo = new javax.swing.JLabel();
        lblZona = new javax.swing.JLabel();
        lblNumeroFuncionario = new javax.swing.JLabel();
        lblNombreFuncionario = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPaquetesTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNoEntregados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEntregados = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblFechaATitulo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lblEnvioTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnvioTitulo.setText("Envío:");

        lblNombreFuncionarioTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreFuncionarioTitulo.setText("Funcionario:");

        lblNumeroFuncionarioTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroFuncionarioTitulo.setText("Numero:");

        lblZonaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblZonaTitulo.setText("Zona:");

        lblPaquetesTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPaquetesTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaquetesTitulo.setText("Paquetes no entregados");

        lblZona.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblZona.setText("SUR");

        lblNumeroFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNumeroFuncionario.setText("123");

        lblNombreFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNombreFuncionario.setText("Nombre");

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblID.setText("0");

        lblPaquetesTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPaquetesTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPaquetesTitulo1.setText("Paquetes entregados");

        lstNoEntregados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstNoEntregados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstNoEntregados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNoEntregadosMouseClicked(evt);
            }
        });
        lstNoEntregados.addListSelectionListener(this::lstNoEntregadosValueChanged);
        jScrollPane1.setViewportView(lstNoEntregados);

        lstEntregados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstEntregados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEntregados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEntregadosMouseClicked(evt);
            }
        });
        lstEntregados.addListSelectionListener(this::lstEntregadosValueChanged);
        jScrollPane2.setViewportView(lstEntregados);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setText(">>");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemover.setText("<<");
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Haga doble click para ver detalles del paquete");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblFechaATitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaATitulo.setText("Fecha:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblFecha.setText("11/11/11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFechaATitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEnvioTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreFuncionarioTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(lblNumeroFuncionarioTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZonaTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblNumeroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPaquetesTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPaquetesTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnvioTitulo)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreFuncionarioTitulo)
                    .addComponent(lblNombreFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroFuncionarioTitulo)
                    .addComponent(lblNumeroFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZonaTitulo)
                    .addComponent(lblZona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaATitulo)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaquetesTitulo)
                    .addComponent(lblPaquetesTitulo1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnRemover)
                        .addGap(34, 34, 34)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Agrega un paquete a los paquetes entregados
     * @param evt Click sobre el boton
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Paquete paquete = lstNoEntregados.getSelectedValue();
        if(paquete != null){
            agregarALstPaquetes(paquete, lstEntregados);
            eliminarDeLstPaquetes(paquete,lstNoEntregados);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    /**
     * Remueve un paquete de los paquetes entregados
     * @param evt Click sobre el boton
     */
    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        Paquete paquete = lstEntregados.getSelectedValue();
        if(paquete != null){
            agregarALstPaquetes(paquete, lstNoEntregados);
            eliminarDeLstPaquetes(paquete,lstEntregados);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * Agrega un paquete a la listData de un jlist
     * @param paquete Paquete a agregar
     * @param lista Lista a la que se tiene que agregar el paquete
     */
    private void agregarALstPaquetes(Paquete paquete, JList<Paquete> lista){
        ListModel<Paquete> modelo = lista.getModel();
        ArrayList<Paquete> items = getPaquetesDeLista(lista);
        items.add(paquete);
        
        Collections.sort(items);
        
        lista.setListData(items.toArray(Paquete[]::new));
    }
    
    /**
     * Elimina un paquete de la listData de un jlist
     * @param paquete Paquete a eliminar
     * @param lista Lista a la que se le debe eliminar el paquete
     */
    private void eliminarDeLstPaquetes(Paquete paquete, JList<Paquete> lista){
        ListModel<Paquete> modelo = lista.getModel();
        ArrayList<Paquete> items = getPaquetesDeLista(lista);
        
        items.remove(paquete);
        
        lista.setListData(items.toArray(Paquete[]::new));
    }
    
    /**
     * Obtiene una lista de paquetes de un Jlist
     * @param lista Jlist a la que se le tienen que obtener sus paquetes
     * @return ArrayList con los paquetes del jlist
     */
    public ArrayList<Paquete> getPaquetesDeLista(JList<Paquete> lista){
        ListModel<Paquete> modelo = lista.getModel();
        ArrayList<Paquete> items = new ArrayList<Paquete>(); // Paquete[modelo.getSize() + 1];
        for (int i = 0; i < modelo.getSize(); i = i + 1) {
            items.add(modelo.getElementAt(i));
        }
        Collections.sort(items);
        return items;
    }
    
    private void lstEntregadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntregadosValueChanged
        if (!evt.getValueIsAdjusting()) {
            Paquete p = lstEntregados.getSelectedValue();
            if (p != null) {
                btnRemover.setEnabled(true);
            } else {
                btnRemover.setEnabled(false);
            }
        }
    }//GEN-LAST:event_lstEntregadosValueChanged

    private void lstNoEntregadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNoEntregadosValueChanged
        if (!evt.getValueIsAdjusting()) {
            Paquete p = lstNoEntregados.getSelectedValue();
            if (p != null) {
                btnAgregar.setEnabled(true);
            } else {
                btnAgregar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_lstNoEntregadosValueChanged

    private void lstEntregadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEntregadosMouseClicked
        if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1){
            Paquete p = lstEntregados.getSelectedValue();
            if(p != null){
                new VentanaDetallePaquete(p).setVisible(true); 
            }
        }
    }//GEN-LAST:event_lstEntregadosMouseClicked

    private void lstNoEntregadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNoEntregadosMouseClicked
        if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1){
            Paquete p = lstNoEntregados.getSelectedValue();
            if(p != null){
                new VentanaDetallePaquete(p).setVisible(true); 
            }
        }
    }//GEN-LAST:event_lstNoEntregadosMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        VentanaRecepcion nueva = new VentanaRecepcion(sistema);
        nueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "Una vez recibido el envio, no se puede modificar. \nEstá seguro de los cambios?", "¡ATENCIÓN!",
                JOptionPane.YES_NO_OPTION);
        
        if(confirmacion == JOptionPane.YES_OPTION){
            ArrayList<Paquete> paquetesABorrar = this.getPaquetesDeLista(lstNoEntregados);
            this.getSistema().RecibirEnvio(this.getEnvio(), paquetesABorrar);
            
            //Mostrar mensaje de exito, cerrar la ventana y abrir la anterior
            JOptionPane.showMessageDialog(this, "Envío recibido correctamente.");
            dispose();
            VentanaRecepcion nueva = new VentanaRecepcion(sistema);
            nueva.setVisible(true);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEnvioTitulo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaATitulo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombreFuncionario;
    private javax.swing.JLabel lblNombreFuncionarioTitulo;
    private javax.swing.JLabel lblNumeroFuncionario;
    private javax.swing.JLabel lblNumeroFuncionarioTitulo;
    private javax.swing.JLabel lblPaquetesTitulo;
    private javax.swing.JLabel lblPaquetesTitulo1;
    private javax.swing.JLabel lblZona;
    private javax.swing.JLabel lblZonaTitulo;
    private javax.swing.JList<Paquete> lstEntregados;
    private javax.swing.JList<Paquete> lstNoEntregados;
    // End of variables declaration//GEN-END:variables
}
