//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JOptionPane;
import Controladores.Sistema;
import Excepciones.ErrorCargaArchivoMalformado;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null); //Para que la ventana aparezca en el medio de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_1 = new javax.swing.JLabel();
        Nuevo = new javax.swing.JToggleButton();
        Guardado = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lbl_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setText("Seleccione como quiere iniciar el sistema:");

        Nuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nuevo.setText("Sistema Nuevo");
        Nuevo.addActionListener(this::SistemaNuevo);

        Guardado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Guardado.setText("Sistema con Datos Guardados");
        Guardado.addActionListener(this::SistemaGuardado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Guardado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_1)
                .addGap(18, 18, 18)
                .addComponent(Nuevo)
                .addGap(18, 18, 18)
                .addComponent(Guardado)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SistemaNuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SistemaNuevo
        
        //Salta un cuadro que pide verificar, con un si o no
        int verifico = JOptionPane.showConfirmDialog(this, "Si crea un sistema nuevo,"
                + " se borraran los datos del sistema actualmente guardado.\n¿Desea continuar?", "¡ATENCIÓN!",
                JOptionPane.YES_NO_OPTION);
        
        if(verifico == JOptionPane.YES_OPTION){ //Si dice que si, se crea un sistema nuevo
            Sistema nuevo = new Sistema();
            nuevo.sistemaNuevo(); //Llama al metodo del sistema nuevo que crea los archivos vacios
            Menu menu = new Menu();
            menu.setSistema(nuevo); //Le paso el sistema elegido
            menu.setVisible(true);
            dispose();    
        }
    }//GEN-LAST:event_SistemaNuevo

    private void SistemaGuardado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SistemaGuardado
        try {
            Sistema guardado = new Sistema();
            guardado.sistemaGuardado(); //Llama al metodo del sistema que carga el archivo guardado
            Menu menu = new Menu();
            menu.setSistema(guardado); //Le paso el sistema elegido
            menu.setVisible(true);
            dispose();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Ocurrió un error al cargar los archivos guardados, revise el formato o comience un sistema nuevo.", "Error al cargar datos", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SistemaGuardado

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Guardado;
    private javax.swing.JToggleButton Nuevo;
    private javax.swing.JLabel lbl_1;
    // End of variables declaration//GEN-END:variables
}//Class