//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import Controladores.Sistema;
import Modelo.Envio;
import Modelo.Paquete;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collections;

public class VentanaDetallesEnvio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaDetallesEnvio.class.getName());
    private Sistema sistema;
    private Envio envio;
    
    //<editor-fold desc="Getter y setters">
    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    
    public Envio getEnvio() {
        return envio;
    }

    public void setEnvio(Envio envio) {
        this.envio = envio;
    }
    //</editor-fold>

    /**
     * Creates new form VentanaDetallesEnvio
     */
    public VentanaDetallesEnvio(Sistema sistema, Envio envio) {
        initComponents();
        setLocationRelativeTo(null); 
        this.setSistema(sistema);
        this.setEnvio(envio);
        lblID.setText("" + this.getEnvio().getNumeroEnvio());
        lblNombreFuncionario.setText(this.getEnvio().getFuncionario().getNombre());
        lblNumeroFuncionario.setText("" + this.getEnvio().getFuncionario().getNumero());
        lblZona.setText(this.getEnvio().getNombreZona());
        lblFecha.setText(this.getEnvio().getFechaEnvio().toString());
        cargarPaquetes();
        
        this.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                VentanaRecepcion nueva = new VentanaRecepcion(sistema);
                nueva.setVisible(true);
            }
        });
    }
    
    public void cargarPaquetes(){
        ArrayList<Paquete> paquetes = new ArrayList<Paquete>(this.getEnvio().getPaquetes());
        Collections.sort(paquetes);
        lstPaquetes.setListData(paquetes.toArray(Paquete[]::new));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrPaquetes = new javax.swing.JScrollPane();
        lstPaquetes = new javax.swing.JList<>();
        lblEnvioTitulo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNombreFuncionarioTitulo = new javax.swing.JLabel();
        lblNombreFuncionario = new javax.swing.JLabel();
        lblNumeroFuncionarioTitulo = new javax.swing.JLabel();
        lblNumeroFuncionario = new javax.swing.JLabel();
        lblZonaTitulo = new javax.swing.JLabel();
        lblZona = new javax.swing.JLabel();
        lblPaquetesTitulo = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();
        lblFechaTitulo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalles de envío");

        lstPaquetes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPaquetesMouseClicked(evt);
            }
        });
        scrPaquetes.setViewportView(lstPaquetes);

        lblEnvioTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnvioTitulo.setText("Envío:");

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblID.setText("0");

        lblNombreFuncionarioTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreFuncionarioTitulo.setText("Funcionario:");

        lblNombreFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNombreFuncionario.setText("Nombre");

        lblNumeroFuncionarioTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroFuncionarioTitulo.setText("Numero:");

        lblNumeroFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNumeroFuncionario.setText("123");

        lblZonaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblZonaTitulo.setText("Zona:");

        lblZona.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblZona.setText("SUR");

        lblPaquetesTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPaquetesTitulo.setText("Paquetes:");

        lblAyuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAyuda.setText("Haga doble click para ver detalles del paquete");

        lblFechaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaTitulo.setText("Fecha:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblFecha.setText("11/11/11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFechaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPaquetesTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(lblNumeroFuncionarioTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(lblNombreFuncionarioTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEnvioTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblZonaTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(0, 0, 0)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNombreFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblZona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addComponent(lblNumeroFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnvioTitulo)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreFuncionarioTitulo)
                    .addComponent(lblNombreFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroFuncionarioTitulo)
                    .addComponent(lblNumeroFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZonaTitulo)
                    .addComponent(lblZona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaTitulo)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaquetesTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAyuda)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPaquetesMouseClicked
        if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1){
            Paquete p = lstPaquetes.getSelectedValue();
            if(p != null){
                new VentanaDetallePaquete(p).setVisible(true); 
            }
        }
    }//GEN-LAST:event_lstPaquetesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblEnvioTitulo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaTitulo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombreFuncionario;
    private javax.swing.JLabel lblNombreFuncionarioTitulo;
    private javax.swing.JLabel lblNumeroFuncionario;
    private javax.swing.JLabel lblNumeroFuncionarioTitulo;
    private javax.swing.JLabel lblPaquetesTitulo;
    private javax.swing.JLabel lblZona;
    private javax.swing.JLabel lblZonaTitulo;
    private javax.swing.JList<Paquete> lstPaquetes;
    private javax.swing.JScrollPane scrPaquetes;
    // End of variables declaration//GEN-END:variables
}
