//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import Interfaz.VentanaPrincipal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer; //Para el timer

public class VentanaBienvenida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaBienvenida.class.getName());

    public VentanaBienvenida() {
        initComponents(); //Llama a la ventana de bienvenida
        setLocationRelativeTo(null); //Para que la ventana aparezca en el medio de la pantalla

        //Poner un timer de 3 segundos para abrir la ventana que va despues la de bienvenida
        Timer t = new Timer(3000, new ActionListener(){
            public void actionPerformed(ActionEvent e){
                new VentanaPrincipal().setVisible(true);//Abre la ventana principal despues de 3 segundos
                dispose();//Cierra la de bienvenida
            }
        });
        t.setRepeats(false);//Para que no quede en un loop la ventana que se abre
        t.start(); //Inicia el timer
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setText("Programa creado por:");
        getContentPane().add(lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 255, -1));

        lbl_2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_2.setText("212712 - Veronica Busiello");
        getContentPane().add(lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 255, -1));

        lbl_3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lbl_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_3.setText("354398 - Lourdes Ayala");
        getContentPane().add(lbl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 255, -1));

        lbl_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_4.setText("Programación 2 - Primer Semestre 2026");
        getContentPane().add(lbl_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 340, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borde.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    // End of variables declaration//GEN-END:variables
}//Class