//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controladores.Sistema;
import Modelo.Cliente;

public class VentanaModificarCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaModificarCliente.class.getName());

    private Sistema sistema; //Objeto sistema
    private String nombreActual; //Objeto del cliente que le pasan a la ventana
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    
    public VentanaModificarCliente(Sistema unSistema, Cliente unCliente){
        initComponents();
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.sistema = unSistema;
        this.nombreActual = unCliente.getNombre();
        
        //Pongo los datos actuales del cliente en la ventana
        nombreA.setText(unCliente.getNombre());
        celularA.setText(unCliente.getCelular());
        correoA.setText(unCliente.getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Guardar = new javax.swing.JToggleButton();
        Cancelar = new javax.swing.JToggleButton();
        lbl = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoCelular = new javax.swing.JTextField();
        TextoCorreo = new javax.swing.JTextField();
        NombreN = new javax.swing.JLabel();
        CelularN = new javax.swing.JLabel();
        CorreoN = new javax.swing.JLabel();
        nombreA = new javax.swing.JLabel();
        celularA = new javax.swing.JLabel();
        correoA = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre Actual:");

        Celular.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Celular.setText("Celular Actual:");

        Correo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correo.setText("Correo Actual:");

        Guardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(this::ModificarCliente);

        Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(this::Cancelar);

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Ingrese los datos a modificar:");

        TextoNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        TextoCelular.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        TextoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        NombreN.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        NombreN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreN.setText("Nombre Nuevo:");

        CelularN.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        CelularN.setText("Celular Nuevo:");

        CorreoN.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        CorreoN.setText("Correo Nuevo:");

        nombreA.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreA.setText("Nombre");

        celularA.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        celularA.setText("000000000");

        correoA.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        correoA.setText("correo@dominio.com");

        lblAyuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAyuda.setText("Los campos que queden vacios no se modificaran.");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Modificar  Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Celular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(celularA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(correoA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(NombreN))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CelularN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CorreoN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextoCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextoCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreN)
                    .addComponent(nombreA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celular)
                    .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CelularN)
                    .addComponent(celularA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CorreoN)
                    .addComponent(correoA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAyuda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Si no quiere modificar, se cierra sin hacer nada
    private void Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar
        VentanaCliente nueva = new VentanaCliente(sistema);
        nueva.setVisible(true); 
        dispose();
    }//GEN-LAST:event_Cancelar

    //Metodo que utilizo para sacar los datos que ingresan y luego guardar lo modificado
    private void ModificarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarCliente

        String nombre = TextoNombre.getText().trim();
        String celular = TextoCelular.getText().trim();
        String correo = TextoCorreo.getText().trim();
        
        //Le paso el nombre actual para buscar en la lista el objeto cliente a modificar y los datos
        if(sistema.ModificarCliente(this.nombreActual, nombre, celular, correo)){
            JOptionPane.showMessageDialog(this, "Cliente modificado correctamente.");                          
            VentanaCliente nueva = new VentanaCliente(sistema);
            nueva.setVisible(true); 
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Ya existe un cliente o funcionario con ese nombre, ingrese otro.");
        }
    }//GEN-LAST:event_ModificarCliente

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Cancelar;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel CelularN;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel CorreoN;
    private javax.swing.JToggleButton Guardar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreN;
    private javax.swing.JTextField TextoCelular;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JLabel celularA;
    private javax.swing.JLabel correoA;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel nombreA;
    // End of variables declaration//GEN-END:variables
}