//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import Utils.Utils;
import java.util.*;
import javax.swing.JFrame;
import Controladores.Sistema;
import Modelo.Cliente;
import Modelo.Paquete;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaReporteCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReporteCliente.class.getName());
    
    private Sistema sistema; //Objeto sistema
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    
    public VentanaReporteCliente(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); //Para que la ventana aparezca en el medio de la pantalla
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Para que no se cierre todo el programa y solo esta ventana
        
        this.sistema = unSistema;
        cargarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_1 = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setText("Reportes por Cliente");

        lblClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClientes.setText("Clientes ingresados en el sistema:");

        lblAyuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAyuda.setText("Seleccione un cliente de la lista para ver su reporte.");

        ListaClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_1)
                .addGap(18, 18, 18)
                .addComponent(lblClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAyuda)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo para que cuando se seleccione uno de la lista se pueda ver el reporte
    private void ListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaClientesMouseClicked
        
        int fila = ListaClientes.getSelectedRow(); //Saca la fila seleccionada

        if(fila != -1){ //Verifico que la fila exista
            String nombre = ListaClientes.getValueAt(fila, 0).toString(); //Saco el numero de la fila, la columna es 0 porque uso nombre
            Cliente cliente = Utils.encontrarCliente(sistema.getClientes(), nombre);
            
            if(cliente != null){ //Si el cliente existe abro la ventana de reporte
                if(this.getSistema().getPaquetesPorCliente(cliente.getNombre()).size() > 0){
                    VentanaReporteCliente2 nueva = new VentanaReporteCliente2(sistema, cliente);
                    nueva.setVisible(true);
                } else{
                    JOptionPane.showMessageDialog(this, "El cliente seleccionado no tiene paquetes que mostrar.");
                }
            }
        }
    }//GEN-LAST:event_ListaClientesMouseClicked

    //Metodo para que aparezcan los clientes en la lista
    public void cargarClientes(){
        
        DefaultTableModel modelo = new DefaultTableModel(); //Defino una nueva tabla
        modelo.addColumn("Nombre"); //Le pongo el nombre a cada columna
        modelo.addColumn("Total de Paquetes");
        modelo.addColumn("Celular");
        modelo.addColumn("Correo");
        
        //Copio de la lista para no modificar el orden de la original
        ArrayList<Cliente> ordenada = new ArrayList<>(sistema.getClientes());
        
        //Ordenar alfabeticamente por nombre
        Collections.sort(ordenada);
        
        //Para cada cliente lo agrego a la tabla
        for(int i = 0; i < ordenada.size(); i++){
            Cliente c = ordenada.get(i);
            ArrayList<Paquete> paquetesCliente = this.getSistema().getPaquetesPorCliente(c.getNombre());
            int totalPaquetes = paquetesCliente.size();
            modelo.addRow(new Object[]{c.getNombre(),totalPaquetes, c.getCelular(), c.getCorreo()}); 
        }
        
        ListaClientes.setModel(modelo); //Pone los clientes en la tabla
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lbl_1;
    // End of variables declaration//GEN-END:variables
}