//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import Controladores.Sistema;
import Excepciones.ErrorFechaNoValidaException;
import Modelo.Envio;
import Modelo.Fecha;
import Modelo.Funcionario;
import Modelo.Paquete;
import Modelo.Tarifa;
import Utils.Utils;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextField;
import javax.swing.ListModel;
import static Utils.Utils.stringEsParseableAInt;

public class VentanaIngresarEnvio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngresarEnvio.class.getName());
    private Sistema sistema;
    
    public Sistema getSistema() {
        return sistema;
    }

    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    
    /**
     * Creates new form VentanaAgregarEnvio
     */
    public VentanaIngresarEnvio(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); 
        this.setSistema(unSistema);
        this.cargarNumeroEnvio();
        this.cargarZonas();
        this.cargarFuncionarios();
    }

    private void cargarNumeroEnvio(){
        lblID.setText("" + (Envio.getUltimoId() + 1));
    }
    
    private void cargarZonas(){
        ArrayList<String> nombresZonas = new ArrayList<String>();
        nombresZonas.add("Seleccionar");
        Iterator<Tarifa> it = this.getSistema().getTarifas().iterator();
        while(it.hasNext()){ //recorro el arraylist de Tarifas y agrego los nombres de a uno al modelo
            Tarifa t = it.next();
            nombresZonas.add(t.getNombre());
        }
        cmbZona.setModel(new DefaultComboBoxModel(nombresZonas.toArray())); //Asigno la lista modelo al jlist
    }
    
    private void cargarFuncionarios(){
        ArrayList<String> nombresFuncionarios = new ArrayList<String>();
        nombresFuncionarios.add("Seleccionar");
        Iterator<Funcionario> it = this.getSistema().getFuncionarios().iterator();
        while(it.hasNext()){ //recorro el arraylist de funcionarios y los agrego de a uno al modelo
            Funcionario f = it.next();
            nombresFuncionarios.add(f.getNombre());
        }
        cmbFuncionarios.setModel(new DefaultComboBoxModel(nombresFuncionarios.toArray())); //Asigno la lista modelo al jlist
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblNumeroEnvio = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        lblZona = new javax.swing.JLabel();
        cmbZona = new javax.swing.JComboBox<>();
        lblPaquetes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPendientes = new javax.swing.JList<>();
        lblPendientes = new javax.swing.JLabel();
        lblAEnviar = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstAEnviar = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        lblAyuda = new javax.swing.JLabel();
        lblTotalPaquetesTitulo = new javax.swing.JLabel();
        lblPesoTotalTitulo = new javax.swing.JLabel();
        lblTotalPaquetes = new javax.swing.JLabel();
        lblPesoTotal = new javax.swing.JLabel();
        lblNoPaquetes = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        cmbFuncionarios = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lblNumeroEnvio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblNumeroEnvio.setText("Número de envio:");

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblID.setText("1");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblFecha.setText("Fecha de envio:");

        txtAnio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarAnio(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("/");

        txtMes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarMes(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("/");

        txtDia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarDia(evt);
            }
        });

        lblZona.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblZona.setText("Zona:");

        cmbZona.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbZona.addActionListener(this::cmbZonaActionPerformed);

        lblPaquetes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPaquetes.setText("Paquetes a enviar:");

        lstPendientes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lstPendientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPendientesMouseClicked(evt);
            }
        });
        lstPendientes.addListSelectionListener(this::lstPendientesValueChanged);
        jScrollPane2.setViewportView(lstPendientes);

        lblPendientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendientes.setText("Pendientes");

        lblAEnviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAEnviar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAEnviar.setText("A enviar");

        lstAEnviar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lstAEnviar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAEnviarMouseClicked(evt);
            }
        });
        lstAEnviar.addListSelectionListener(this::lstAEnviarValueChanged);
        jScrollPane3.setViewportView(lstAEnviar);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setText(">>");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnRemover.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemover.setText("<<");
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(this::btnRemoverActionPerformed);

        lblAyuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAyuda.setText("Haga doble click para ver detalles del paquete");

        lblTotalPaquetesTitulo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTotalPaquetesTitulo.setText("Paquetes a enviar:");

        lblPesoTotalTitulo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPesoTotalTitulo.setText("Peso total del envio:");

        lblTotalPaquetes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTotalPaquetes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPaquetes.setText("0");

        lblPesoTotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPesoTotal.setText("0 grs.");

        lblNoPaquetes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNoPaquetes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoPaquetes.setText("Seleccionar una zona con paquetes");

        lblFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblFuncionario.setText("Funcionario:");

        cmbFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbFuncionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nuevo Envío");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPesoTotalTitulo)
                            .addComponent(lblTotalPaquetesTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPesoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalPaquetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeroEnvio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNoPaquetes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblAEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addComponent(lblAyuda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblZona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPaquetes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbFuncionarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbZona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroEnvio)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(cmbFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFecha)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblZona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPaquetes))
                    .addComponent(cmbZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNoPaquetes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPendientes)
                    .addComponent(lblAEnviar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAgregar)
                        .addGap(28, 28, 28)
                        .addComponent(btnRemover)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAyuda)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPaquetesTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTotalPaquetes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesoTotalTitulo)
                    .addComponent(lblPesoTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            boolean esValido = true;
            
            Funcionario funcionario = this.getSistema().encontrarFuncionario(cmbFuncionarios.getSelectedItem().toString());
            
            //Parseo de fecha -> Tira excepcion si no son valores numericos
            int dia = Integer.parseInt(txtDia.getText().trim());                                     
            int mes = Integer.parseInt(txtMes.getText().trim());
            int anio = Integer.parseInt(txtAnio.getText().trim());
            Fecha fecha = Fecha.parseFecha(dia, mes, anio); //-> tira excepcion si es una fecha invalida
            
            String nombreZona = cmbZona.getSelectedItem().toString();
            
            ArrayList<Paquete> paquetes = getPaquetesDeLista(lstAEnviar);
            
            esValido &= !(funcionario == null || nombreZona.isEmpty() || paquetes.isEmpty()); //Ningun valor esta vacio
            if(esValido){
                if(!sistema.guardarEnvio(funcionario, fecha, nombreZona, paquetes)){
                    JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar el envío.", "Error al guardar envío", ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Envío guardado correctamente.");
                    this.dispose();
                } 
            } else{
                if(paquetes.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Debe agregar al menos 1 paquete a enviar.", "Error al guardar envío", ERROR_MESSAGE);  
                } else{
                    JOptionPane.showMessageDialog(this, "Debe ingresar un todos los datos.", "Error al guardar envío", ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException ex){
            //Loggear el error
            JOptionPane.showMessageDialog(this, "La fecha debe contener valores numéricos.", "Error al guardar envío", ERROR_MESSAGE);
        } catch(ErrorFechaNoValidaException ex) {
            //Loggear el error
            JOptionPane.showMessageDialog(this, "El formato de fecha es inválida o se ingresó una fecha incorrecta.", "Error al guardar envío", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * Obtiene una lista de paquetes de un Jlist
     * @param lista Jlist a la que se le tienen que obtener sus paquetes
     * @return ArrayList con los paquetes del jlist
     */
    public ArrayList<Paquete> getPaquetesDeLista(JList<Paquete> lista){
        ListModel<Paquete> modelo = lista.getModel();
        ArrayList<Paquete> items = new ArrayList<Paquete>(); // Paquete[modelo.getSize() + 1];
        for (int i = 0; i < modelo.getSize(); i = i + 1) {
            items.add(modelo.getElementAt(i));
        }
        Collections.sort(items);
        return items;
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Paquete paquete = lstPendientes.getSelectedValue();
        if(paquete != null){
            agregarALstPaquetes(paquete, lstAEnviar);
            eliminarDeLstPaquetes(paquete,lstPendientes);
            lblTotalPaquetes.setText("" + lstAEnviar.getModel().getSize());
            actualizarPesoTotal();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Agrega un paquete a la listData de un jlist
     * @param paquete Paquete a agregar
     * @param lista Lista a la que se tiene que agregar el paquete
     */
    private void agregarALstPaquetes(Paquete paquete, JList<Paquete> lista){
        ListModel<Paquete> modelo = lista.getModel();
        ArrayList<Paquete> items = getPaquetesDeLista(lista);
        items.add(paquete);
        
        Collections.sort(items);
        
        lista.setListData(items.toArray(Paquete[]::new));
    }
    
    /**
     * Elimina un paquete de la listData de un jlist
     * @param paquete Paquete a eliminar
     * @param lista Lista a la que se le debe eliminar el paquete
     */
    private void eliminarDeLstPaquetes(Paquete paquete, JList<Paquete> lista){
        ListModel<Paquete> modelo = lista.getModel();
        ArrayList<Paquete> items = getPaquetesDeLista(lista);
        
        items.remove(paquete);
        
        lista.setListData(items.toArray(Paquete[]::new));
    }
    
    private void validarDia(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarDia
        String dia = txtDia.getText().trim();
        if(dia.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            boolean esValido = stringEsParseableAInt(dia) && Integer.parseInt(dia) > 0 && Integer.parseInt(dia) < 32;
            if(!esValido){ //Si el dia no es un numero, o no estra entre 1 y 31, mostrar mensaje de error y borrar el dato
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros del 1 al 31.", "Input inválido", ERROR_MESSAGE);
                while(!esValido && dia.length() > 0){
                    borrarUltimoChar(txtDia);
                    dia = txtDia.getText().trim();
                    esValido = stringEsParseableAInt(dia) && Integer.parseInt(dia) > 0 && Integer.parseInt(dia) < 32;
                }
            }
        }
    }//GEN-LAST:event_validarDia

    private void validarMes(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarMes
        String mes = txtMes.getText().trim();
        if(mes.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            boolean esValido = stringEsParseableAInt(mes) && Integer.parseInt(mes) > 0 && Integer.parseInt(mes) < 13;
            if(!esValido){ //Si el dia no es un numero, o no estra entre 1 y 31, mostrar mensaje de error y borrar el dato
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros del 1 al 12.", "Input inválido", ERROR_MESSAGE);
                while(!esValido && mes.length() > 0){
                    borrarUltimoChar(txtMes);
                    mes = txtMes.getText().trim();
                    esValido = stringEsParseableAInt(mes) && Integer.parseInt(mes) > 0 && Integer.parseInt(mes) < 13;
                }
            }
        }
    }//GEN-LAST:event_validarMes

    private void validarAnio(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarAnio
        String anio = txtAnio.getText().trim();
        if(anio.length() > 0 && evt.getKeyCode() != KeyEvent.VK_ENTER){
            boolean esValido = stringEsParseableAInt(anio) && Integer.parseInt(anio) > 0 && Integer.parseInt(anio) < 3000;
            if(!esValido){ //Si el dia no es un numero, o no estra entre 1 y 31, mostrar mensaje de error y borrar el dato
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros del 1 al 2999.", "Input inválido", ERROR_MESSAGE);
                while(!esValido && anio.length() > 0){
                    borrarUltimoChar(txtAnio);
                    anio = txtAnio.getText().trim();
                    esValido = stringEsParseableAInt(anio) && Integer.parseInt(anio) > 0 && Integer.parseInt(anio) < 3000;
                }
            }
        }
    }//GEN-LAST:event_validarAnio

    private void cmbZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbZonaActionPerformed
        //Cargar paquetes pendientes
        String zona = cmbZona.getSelectedItem().toString();
        
        btnAgregar.setEnabled(false);
        btnRemover.setEnabled(false);
        lblTotalPaquetes.setText("0");
        lblPesoTotal.setText("0 grs.");
        if(!zona.equalsIgnoreCase("Seleccionar")){
            ArrayList<Paquete> paquetesPendientes = this.getSistema().getPaquetesPorEstadoYZona("PENDIENTE", zona);
            if(paquetesPendientes.size() > 0){
                Collections.sort(paquetesPendientes);
                
                lstPendientes.setListData(paquetesPendientes.toArray(Paquete[]::new));

                lstAEnviar.setListData(new Paquete[0]);
                
                lblNoPaquetes.setVisible(false);
            } else {
                lstPendientes.setListData(new Paquete[0]);

                lstAEnviar.setListData(new Paquete[0]);
                lblNoPaquetes.setText("No hay paquetes en la zona seleccionada");
                lblNoPaquetes.setVisible(true);
            }
        } else {
            lblNoPaquetes.setText("Seleccionar una zona con paquetes");
            lblNoPaquetes.setVisible(true);
            lstPendientes.setListData(new Paquete[0]);

            lstAEnviar.setListData(new Paquete[0]);
        }
    }//GEN-LAST:event_cmbZonaActionPerformed

    private void lstPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPendientesMouseClicked
        if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1){
            Paquete p = lstPendientes.getSelectedValue();
            if(p != null){
                new VentanaDetallePaquete(p).setVisible(true); 
            }
        }
    }//GEN-LAST:event_lstPendientesMouseClicked

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        Paquete paquete = lstAEnviar.getSelectedValue();
        if(paquete != null){
            agregarALstPaquetes(paquete, lstPendientes);
            eliminarDeLstPaquetes(paquete,lstAEnviar);
            lblTotalPaquetes.setText("" + lstAEnviar.getModel().getSize());
            actualizarPesoTotal();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void actualizarPesoTotal(){
        int pesoTotal = 0;
        ListModel<Paquete> modelo = lstAEnviar.getModel();
        for (int i = 0; i < modelo.getSize(); i = i + 1) {
            pesoTotal +=modelo.getElementAt(i).getPeso();
        }
        lblPesoTotal.setText(Utils.aKilosYgramos(pesoTotal));
    }
    
    private void lstPendientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPendientesValueChanged
        if (!evt.getValueIsAdjusting()) {
            Paquete p = lstPendientes.getSelectedValue();
            if (p != null) {
                btnAgregar.setEnabled(true);
            } else {
                btnAgregar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_lstPendientesValueChanged

    private void lstAEnviarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAEnviarValueChanged
        if (!evt.getValueIsAdjusting()) {
            Paquete p = lstAEnviar.getSelectedValue();
            if (p != null) {
                btnRemover.setEnabled(true);
            } else{
                btnRemover.setEnabled(false);
            }
        }
    }//GEN-LAST:event_lstAEnviarValueChanged

    private void lstAEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAEnviarMouseClicked
        if(evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1){
            Paquete p = lstAEnviar.getSelectedValue();
            if(p != null){
                new VentanaDetallePaquete(p).setVisible(true); 
            }
        }
    }//GEN-LAST:event_lstAEnviarMouseClicked

    private void borrarUltimoChar(JTextField campo){
        String texto = campo.getText();
        if(texto.length() > 0){
            campo.setText(texto.substring(0, texto.length() - 1));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> cmbFuncionarios;
    private javax.swing.JComboBox<String> cmbZona;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAEnviar;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNoPaquetes;
    private javax.swing.JLabel lblNumeroEnvio;
    private javax.swing.JLabel lblPaquetes;
    private javax.swing.JLabel lblPendientes;
    private javax.swing.JLabel lblPesoTotal;
    private javax.swing.JLabel lblPesoTotalTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalPaquetes;
    private javax.swing.JLabel lblTotalPaquetesTitulo;
    private javax.swing.JLabel lblZona;
    private javax.swing.JList<Paquete> lstAEnviar;
    private javax.swing.JList<Paquete> lstPendientes;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    // End of variables declaration//GEN-END:variables
}
