//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controladores.Sistema;
import Modelo.Funcionario;

public class VentanaModificarFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaModificarFuncionario.class.getName());

    private Sistema sistema; //Objeto sistema
    private Funcionario actual; //Objeto del funcionario que le pasan a la ventana
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    public VentanaModificarFuncionario(Sistema unSistema, Funcionario unFuncionario){
        initComponents();
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.sistema = unSistema;
        this.actual = unFuncionario;
        
        nombreA.setText(unFuncionario.getNombre());
        celularA.setText(unFuncionario.getCelular());
        numeroA.setText(unFuncionario.getNumero());
        AnioA.setText(unFuncionario.getAnio());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        Guardar = new javax.swing.JToggleButton();
        Cancelar = new javax.swing.JToggleButton();
        lbl = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoCelular = new javax.swing.JTextField();
        TextoNumero = new javax.swing.JTextField();
        NombreN = new javax.swing.JLabel();
        CelularN = new javax.swing.JLabel();
        CorreoN = new javax.swing.JLabel();
        nombreA = new javax.swing.JLabel();
        celularA = new javax.swing.JLabel();
        numeroA = new javax.swing.JLabel();
        Anio = new javax.swing.JLabel();
        AnioN = new javax.swing.JLabel();
        TextoAnio = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        AnioA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre Actual:");

        Celular.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Celular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Celular.setText("Celular Actual:");

        Numero.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Numero.setText("Numero Actual:");

        Guardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(this::ModificarFuncionario);

        Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(this::Cancelar);

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Ingrese los datos a modificar:");

        TextoNombre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        TextoCelular.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        TextoNumero.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        NombreN.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        NombreN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreN.setText("Nombre Nuevo:");

        CelularN.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        CelularN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CelularN.setText("Celular Nuevo:");

        CorreoN.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        CorreoN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CorreoN.setText("Numero Nuevo:");

        nombreA.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreA.setText("Nombre");

        celularA.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        celularA.setText("000000000");

        numeroA.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        numeroA.setText("00000");

        Anio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Anio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anio.setText("Año Actual:");

        AnioN.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        AnioN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnioN.setText("Año Nuevo:");

        TextoAnio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Los campos que queden vacios no se modificaran.");

        AnioA.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        AnioA.setText("2026");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Celular)
                            .addComponent(Anio)
                            .addComponent(Numero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(celularA, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AnioA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CelularN)
                                .addGap(7, 7, 7))
                            .addComponent(NombreN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CorreoN)
                            .addComponent(AnioN))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(TextoCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(TextoAnio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(TextoNombre)))
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreN)
                    .addComponent(nombreA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celular)
                    .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CelularN)
                    .addComponent(celularA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero)
                    .addComponent(TextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CorreoN)
                    .addComponent(numeroA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anio)
                    .addComponent(TextoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnioN)
                    .addComponent(AnioA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar
        VentanaFuncionario nueva = new VentanaFuncionario(sistema);
        nueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cancelar

    private void ModificarFuncionario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarFuncionario

        String nombreActual = actual.getNombre(); //Guardo el nombre actual
        String nombre = TextoNombre.getText().trim();
        String celular = TextoCelular.getText().trim();
        String numero = TextoNumero.getText().trim();
        String anio = TextoAnio.getText().trim();

        //Le paso el nombre actual para buscar en la lista el objeto funcionario a modificar y los datos
        if(sistema.ModificarFuncionario(nombreActual, nombre, celular, numero, anio)){
            JOptionPane.showMessageDialog(this, "Funcionario modificado correctamente.");
            VentanaFuncionario nueva = new VentanaFuncionario(sistema);
            nueva.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Ya existe un cliente o funcionario con ese nombre, ingrese otro.");
        }           
    }//GEN-LAST:event_ModificarFuncionario


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anio;
    private javax.swing.JLabel AnioA;
    private javax.swing.JLabel AnioN;
    private javax.swing.JToggleButton Cancelar;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel CelularN;
    private javax.swing.JLabel CorreoN;
    private javax.swing.JToggleButton Guardar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreN;
    private javax.swing.JLabel Numero;
    private javax.swing.JTextField TextoAnio;
    private javax.swing.JTextField TextoCelular;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoNumero;
    private javax.swing.JLabel celularA;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel nombreA;
    private javax.swing.JLabel numeroA;
    // End of variables declaration//GEN-END:variables
}