//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controladores.Sistema;

public class VentanaModificarTarifas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaModificarTarifas.class.getName());

    //Le paso los datos del sistema que se elige en la ventana principal
    private Sistema sistema; //Objeto sistema
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    
    public VentanaModificarTarifas(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.sistema = unSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonDecide = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Aumentar = new javax.swing.JRadioButton();
        Disminuir = new javax.swing.JRadioButton();
        Porcentaje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Seleccione la opción que desee e ingrese el porcentaje a modificar:");

        BotonDecide.add(Aumentar);
        Aumentar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Aumentar.setText("Aumento de precios");

        BotonDecide.add(Disminuir);
        Disminuir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Disminuir.setText("Disminución de precios");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Porcentaje a modificar:");

        Modificar.setText("Modificar");
        Modificar.addActionListener(this::MoodificarTarifas);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(this::Cancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Disminuir)
                            .addComponent(Aumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Modificar)
                        .addGap(18, 18, 18)
                        .addComponent(Cancelar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Aumentar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Disminuir)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar)
                    .addComponent(Cancelar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoodificarTarifas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoodificarTarifas
        //TENGO QUE USAR RETURN SINO ME ABRE MUCHAS VENTANAS
        
        String numero = Porcentaje.getText().trim();

        //Verifico que seleccionen un boton
        if(!Aumentar.isSelected() && !Disminuir.isSelected()){
            JOptionPane.showMessageDialog(this, "Debe seleccionar Aumentar o Disminuir.");
            return;
        }
        
        //Valido que haya un numero en el cuadro de texto
        if(numero.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entre 1 y 99.");
            return;
        }
        
        //Valido que se ingrese solo un numero
        try{
            double valido = Double.parseDouble(numero);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entre el 1 y el 99.");
            return;
        }
        
       //Valido que sea entre 1 y 99 para que funcionen bien los metodos
        double porcentaje = Double.parseDouble(numero);
        if(porcentaje < 1 || porcentaje > 99){
            JOptionPane.showMessageDialog(this, "Debe ingresar un número entre el 1 y el 99.");
            return;
        }

        //Si ingresan si en el aviso, pasa a los siguientes if, si ingresan no vuelve a la ventana tarifas
        int verifico = JOptionPane.showConfirmDialog(this,"Si modifica las tarifas se aplicará a todas las categorías "
                     + "y zonas.\n¿Desea continuar?", "¡ATENCIÓN!", JOptionPane.YES_NO_OPTION);
        if(verifico != JOptionPane.YES_OPTION){
            VentanaModificarTarifas nueva = new VentanaModificarTarifas(sistema);
            nueva.setVisible(true);
            this.dispose();
        }
    
        //Aca se llama al metodo que hace los calculos y se le pasa una palabra y el porcentaje
        if(Aumentar.isSelected()){
            sistema.getManagerDatos().modificarTarifas("Aumentar", porcentaje);
            JOptionPane.showMessageDialog(this, "Tarifas aumentadas correctamente.");
        } 
        else if(Disminuir.isSelected()){
            sistema.getManagerDatos().modificarTarifas("Disminuir", porcentaje);
            JOptionPane.showMessageDialog(this, "Tarifas reducidas correctamente.");
        }
        
        //Se vuelve a la ventana tarifas
        VentanaTarifas nueva = new VentanaTarifas(sistema);
        nueva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MoodificarTarifas

    private void Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar
        VentanaTarifas nueva = new VentanaTarifas(sistema);
        nueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cancelar


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aumentar;
    private javax.swing.ButtonGroup BotonDecide;
    private javax.swing.JButton Cancelar;
    private javax.swing.JRadioButton Disminuir;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Porcentaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}