//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JFrame;
import Controladores.Sistema;
import Modelo.Funcionario;
import Utils.Utils;
import java.util.*;
import javax.swing.table.DefaultTableModel;

public class VentanaFuncionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaFuncionario.class.getName());
    
    private Sistema sistema; //Objeto sistema
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    public VentanaFuncionario(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); //Para que la ventana aparezca en el medio de la pantalla
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Para que no se cierre todo el programa y solo esta ventana
        
        this.sistema = unSistema;
        cargarFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_1 = new javax.swing.JLabel();
        NuevoCliente = new javax.swing.JToggleButton();
        lbl_2 = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaFuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionarios");

        lbl_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setText("Seleccione la acción que quiere realizar:");

        NuevoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NuevoCliente.setText("Ingresar Funcionario");
        NuevoCliente.addActionListener(this::IngresarFuncionario);

        lbl_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_2.setText("Funcionarios ingresados en el sistema:");

        lblAyuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAyuda.setText("Para modificar los datos de un funcionario debe seleccionar uno de la lista.");

        ListaFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ListaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaFuncionarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                            .addComponent(lbl_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NuevoCliente)
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_1)
                .addGap(18, 18, 18)
                .addComponent(NuevoCliente)
                .addGap(18, 18, 18)
                .addComponent(lbl_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAyuda)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarFuncionario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarFuncionario

        VentanaIngresarFuncionario nuevoFuncionario = new VentanaIngresarFuncionario(sistema);
        nuevoFuncionario.setVisible(true); 
        dispose();
    }//GEN-LAST:event_IngresarFuncionario

    private void ListaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaFuncionariosMouseClicked

        int fila = ListaFuncionarios.getSelectedRow(); //Saca la fila seleccionada

        if(fila != -1){ //Verifico que la fila exista
            String nombre = ListaFuncionarios.getValueAt(fila, 0).toString();
            Funcionario funcionario = Utils.encontrarFuncionario(sistema.getFuncionarios(), nombre);

            if(funcionario != null){ //Si el cliente existe abro la ventana de modificar
                VentanaModificarFuncionario nueva = new VentanaModificarFuncionario(sistema, funcionario);
                nueva.setVisible(true); 
                this.dispose();
            }
        }
    }//GEN-LAST:event_ListaFuncionariosMouseClicked

    //Metodo para que aparezcan los funcionarios en la lista
    private void cargarFuncionarios(){
        
        DefaultTableModel modelo = new DefaultTableModel(); //Defino una nueva tabla
        modelo.addColumn("Nombre");
        modelo.addColumn("Año de Ingreso"); //Le pongo el nombre a cada columna
        modelo.addColumn("Celular");
        modelo.addColumn("Número de Funcionario");
        
        //Copio de la lista para no modificar el orden de la original
        ArrayList<Funcionario> ordenada = new ArrayList<>(sistema.getFuncionarios());

        //Ordenar decrecientemente por año de ingreso
        Collections.sort(ordenada);
        
        //Para cada funcionario lo agrego a la tabla
        for(int i = 0; i < ordenada.size(); i++){
            Funcionario f = ordenada.get(i);
            modelo.addRow(new Object[]{f.getNombre(), f.getAnio(), f.getCelular(), f.getNumero()});
            //Crea un objeto con los datos que le paso
        }
        
        ListaFuncionarios.setModel(modelo); //Pone los clientes en la tabla
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaFuncionarios;
    private javax.swing.JToggleButton NuevoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    // End of variables declaration//GEN-END:variables
}