//Obligatorio 2 - Programación 2 - Primer Semestre 2026
//(212712) Veronica Busiello - (354398) Lourdes Ayala

package Interfaz;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Controladores.Sistema;

public class VentanaIngresarCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIngresarCliente.class.getName());

    private Sistema sistema; //Objeto sistema
    
    public Sistema getSistema(){ //Para obtener el sistema
        return sistema;
    }
    
    public void setSistema(Sistema unSistema){ //Para guardar el sistema
        sistema = unSistema;
    }
    public VentanaIngresarCliente(Sistema unSistema) {
        initComponents();
        setLocationRelativeTo(null); 
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.sistema = unSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Guardar = new javax.swing.JToggleButton();
        Cancelar = new javax.swing.JToggleButton();
        lbl = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoCelular = new javax.swing.JTextField();
        TextoCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre:");

        Celular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Celular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Celular.setText("Celular:");

        Correo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correo.setText("Correo:");

        Guardar.setText("Guardar");
        Guardar.addActionListener(this::GuardarCliente);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(this::Cancelar);

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Ingrese los siguientes datos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nombre)
                                .addComponent(Celular)
                                .addComponent(Correo))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celular)
                    .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar
        VentanaCliente nueva = new VentanaCliente(sistema);
        nueva.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cancelar

    private void GuardarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCliente
        
        String nombre = TextoNombre.getText().trim();
        String celular = TextoCelular.getText().trim();
        String correo = TextoCorreo.getText().trim();

        //Validar
        if(nombre.isEmpty() || celular.isEmpty() || correo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre, un celular y un correo.");
        }
        else{
            //Guardar en el sistema
            if(!sistema.guardarCliente(nombre, celular, correo)){
                JOptionPane.showMessageDialog(this, "Ya existe un cliente o funcionario con ese nombre, ingrese otro.");
            }
            else{
                JOptionPane.showMessageDialog(this, "Cliente guardado correctamente.");
                VentanaCliente nueva = new VentanaCliente(sistema);
                nueva.setVisible(true);
                this.dispose();
            }            
        }
    }//GEN-LAST:event_GuardarCliente


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Cancelar;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Correo;
    private javax.swing.JToggleButton Guardar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField TextoCelular;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}